[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
select = [
    "F", # flake8 (pyflakes)
    "E",    # pycodestyle errors
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "BLE", # flake8-blind-except
    "B",   # flake8-bugbear
    "A",    # flake8-builtins
    "PIE", # flake8-pie
    "RET", # flake8-return
    "SLF", # flake8-self
    "SIM",  # flake8-simplify
    "TID",  # flask8-tidy-imports
    "TCH", # flake8-type-checking
    "PTH",  # flake8-use-pathlib
    "NPY",  # numpy-specific rules
    "PERF", # perflint
    "FURB", # refurb
    "RUF", # ruff-specific rules
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "single"

[tool.ruff.format]
quote-style = "single"
preview = true
